"""
Project Euler - Problem 2

Name: Even Fibonacci numbers

Description:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def even_fibonacci_sum(num_below):

    num_1, num_2 = 1, 2
    n = 0

    even_fib = [2] if 2 < num_below else []

    while n < num_below:
        n = num_1 + num_2

        if n % 2 == 0:
            even_fib.append(n)
        
        num_1, num_2 = num_2, n
    
    return sum(even_fib)


print(even_fibonacci_sum(4_000_000))